<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sri Lakshmi Sudha Ganni">
<meta name="dcterms.date" content="2024-06-18">

<title>Sri Lakshmi - DA Portfolio - Manuscript/Report Template for a Data Analysis Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Sri Lakshmi - DA Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../../../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sls-chundru/sriganni-P2-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Manuscript/Report Template for a Data Analysis Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sri Lakshmi Sudha Ganni </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 18, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Collin Real Contributed to this exercise</p>
<p>The structure below is one possible setup for a data analysis project (including the course project). For a manuscript, adjust as needed. You don’t need to have exactly these sections, but the content covering those sections should be addressed.</p>
<p>This uses MS Word as output format. <a href="https://quarto.org/docs/output-formats/ms-word.html">See here</a> for more information. You can switch to other formats, like html or pdf. See <a href="https://quarto.org/">the Quarto documentation</a> for other formats.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'here' was built under R version 4.3.3</code></pre>
</div>
</div>
<section id="summaryabstract" class="level1">
<h1>Summary/Abstract</h1>
<p><em>Write a summary of your project.</em></p>
<div style="page-break-after: always;"></div>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="general-background-information" class="level2">
<h2 class="anchored" data-anchor-id="general-background-information">General Background Information</h2>
<p><em>Provide enough background on your topic that others can understand the why and how of your analysis</em></p>
</section>
<section id="description-of-data-and-data-source" class="level2">
<h2 class="anchored" data-anchor-id="description-of-data-and-data-source">Description of data and data source</h2>
<p><em>Describe what the data is, what it contains, where it is from, etc. Eventually this might be part of a methods section.</em></p>
<p>The original data is a simple made-up data-set in an Excel file which is exampledata.xlsx.The dataset contains the variables Height, weight and Gender columns of a few imaginary individuals.It is a small dataset with 15 rows and 3 columns.The dataset purposefully contains some faulty entries that need to be cleaned. The data is used to demonstrate the analysis of the data using R. I have added 2 columns to the data which are Income and Eye Color. The data is saved as exampledata2.xlsx. I also added descriptions for the new variables to the codebook sheet in the excel file.</p>
</section>
<section id="questionshypotheses-to-be-addressed" class="level2">
<h2 class="anchored" data-anchor-id="questionshypotheses-to-be-addressed">Questions/Hypotheses to be addressed</h2>
<p><em>State the research questions you plan to answer with this analysis.</em></p>
<p>To cite other work (important everywhere, but likely happens first in introduction), make sure your references are in the bibtex file specified in the YAML header above (here <code>dataanalysis_template_references.bib</code>) and have the right bibtex key. Then you can include like this:</p>
<p>Examples of reproducible research projects can for instance be found in <span class="citation" data-cites="mckay2020 mckay2020a">(<a href="#ref-mckay2020" role="doc-biblioref">McKay, Ebell, Billings, et al., 2020</a>; <a href="#ref-mckay2020a" role="doc-biblioref">McKay, Ebell, Dale, Shen, &amp; Handel, 2020</a>)</span></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p><em>Describe your methods. That should describe the data, the cleaning processes, and the analysis approaches. You might want to provide a shorter description here and all the details in the supplement.</em></p>
<section id="data-aquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-aquisition">Data aquisition</h2>
<p><em>As applicable, explain where and how you got the data. If you directly import the data from an online source, you can combine this section with the next.</em></p>
</section>
<section id="data-import-and-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-import-and-cleaning">Data import and cleaning</h2>
<p><em>Write code that reads in the file and cleans it so it’s ready for analysis. Since this will be fairly long code for most datasets, it might be a good idea to have it in one or several R scripts. If that is the case, explain here briefly what kind of cleaning/processing you do, and provide more details and well documented code somewhere (e.g.&nbsp;as supplement in a paper). All materials, including files that contain code, should be commented well so everyone can follow along.</em></p>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical analysis</h2>
<p><em>Explain anything related to your statistical analyses.</em></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="exploratorydescriptive-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratorydescriptive-analysis">Exploratory/Descriptive analysis</h2>
<p><em>Use a combination of text/tables/figures to explore and describe your data. Show the most important descriptive results here. Additional ones should go in the supplement. Even more can be in the R and Quarto files that are part of your project.</em></p>
<p><a href="#tbl-summarytable">Table&nbsp;1</a> shows a summary of the data.</p>
<p>Note the loading of the data providing a <strong>relative</strong> path using the <code>../../</code> notation. (Two dots means a folder up). You never want to specify an <strong>absolute</strong> path like <code>C:\ahandel\myproject\results\</code> because if you share this with someone, it won’t work for them since they don’t have that path. You can also use the <code>here</code> R package to create paths. See examples of that below. <strong>I recommend the <code>here</code> package, but I’m showing the other approach here just in case you encounter it.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-summarytable" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Data summary table.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_type</th>
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">factor.ordered</th>
<th style="text-align: right;">factor.n_unique</th>
<th style="text-align: left;">factor.top_counts</th>
<th style="text-align: right;">numeric.mean</th>
<th style="text-align: right;">numeric.sd</th>
<th style="text-align: right;">numeric.p0</th>
<th style="text-align: right;">numeric.p25</th>
<th style="text-align: right;">numeric.p50</th>
<th style="text-align: right;">numeric.p75</th>
<th style="text-align: right;">numeric.p100</th>
<th style="text-align: left;">numeric.hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">F: 4, M: 4, O: 2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Eye Color</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">blu: 4, bro: 2, haz: 2, bla: 1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">Height</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">165.60000</td>
<td style="text-align: right;">15.06431</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">158.25</td>
<td style="text-align: right;">166</td>
<td style="text-align: right;">177.25</td>
<td style="text-align: right;">183</td>
<td style="text-align: left;">▂▁▃▆▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">Weight</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">70.11111</td>
<td style="text-align: right;">21.24526</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">55.00</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">110</td>
<td style="text-align: left;">▇▂▃▂▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">Income</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">87000.00000</td>
<td style="text-align: right;">14613.54014</td>
<td style="text-align: right;">60000</td>
<td style="text-align: right;">81250.00</td>
<td style="text-align: right;">87000</td>
<td style="text-align: right;">95750.00</td>
<td style="text-align: right;">110000</td>
<td style="text-align: left;">▅▂▇▇▂</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="basic-statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="basic-statistical-analysis">Basic statistical analysis</h2>
<p><em>To get some further insight into your data, if reasonable you could compute simple statistics (e.g.&nbsp;simple models with 1 predictor) to look for associations between your outcome(s) and each individual predictor variable. Though note that unless you pre-specified the outcome and main exposure, any “p&lt;0.05 means statistical significance” interpretation is not valid.</em></p>
<p><a href="#fig-result">Figure&nbsp;1</a> shows a scatterplot figure produced by one of the R scripts.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-result" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../../results/figures/height-weight-stratified.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Height and weight stratified by gender.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="full-analysis" class="level2">
<h2 class="anchored" data-anchor-id="full-analysis">Full analysis</h2>
<p><em>Use one or several suitable statistical/machine learning methods to analyze your data and to produce meaningful figures, tables, etc. This might again be code that is best placed in one or several separate R scripts that need to be well documented. You want the code to produce figures and data ready for display as tables, and save those. Then you load them here.</em></p>
<p>Example <a href="#tbl-resulttable2">Table&nbsp;2</a> shows a summary of a linear model fit.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-resulttable2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2: Linear model fit table.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">149.2726967</td>
<td style="text-align: right;">23.3823360</td>
<td style="text-align: right;">6.3839942</td>
<td style="text-align: right;">0.0013962</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight</td>
<td style="text-align: right;">0.2623972</td>
<td style="text-align: right;">0.3512436</td>
<td style="text-align: right;">0.7470519</td>
<td style="text-align: right;">0.4886517</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GenderM</td>
<td style="text-align: right;">-2.1244913</td>
<td style="text-align: right;">15.5488953</td>
<td style="text-align: right;">-0.1366329</td>
<td style="text-align: right;">0.8966520</td>
</tr>
<tr class="even">
<td style="text-align: left;">GenderO</td>
<td style="text-align: right;">-4.7644739</td>
<td style="text-align: right;">19.0114155</td>
<td style="text-align: right;">-0.2506112</td>
<td style="text-align: right;">0.8120871</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="summary-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="summary-and-interpretation">Summary and Interpretation</h2>
<p><em>Summarize what you did, what you found and what it means.</em></p>
</section>
<section id="strengths-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="strengths-and-limitations">Strengths and Limitations</h2>
<p><em>Discuss what you perceive as strengths and limitations of your analysis.</em></p>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p><em>What are the main take-home messages?</em></p>
<p><em>Include citations in your Rmd file using bibtex, the list of references will automatically be placed at the end</em></p>
<p>This paper <span class="citation" data-cites="leek2015">(<a href="#ref-leek2015" role="doc-biblioref">Leek &amp; Peng, 2015</a>)</span> discusses types of analyses.</p>
<p>These papers <span class="citation" data-cites="mckay2020 mckay2020a">(<a href="#ref-mckay2020" role="doc-biblioref">McKay, Ebell, Billings, et al., 2020</a>; <a href="#ref-mckay2020a" role="doc-biblioref">McKay, Ebell, Dale, et al., 2020</a>)</span> are good examples of papers published using a fully reproducible setup similar to the one shown in this template.</p>
<p>Note that this cited reference will show up at the end of the document, the reference formatting is determined by the CSL file specified in the YAML header. Many more style files for almost any journal <a href="https://www.zotero.org/styles">are available</a>. You also specify the location of your bibtex reference file in the YAML. You can call your reference file anything you like, I just used the generic word <code>references.bib</code> but giving it a more descriptive name is probably better.</p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-result1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../../results/figures/boxplot.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Height and weight stratified by gender.</figcaption>
</figure>
</div>
</div>
</div>
<p>The Boxplot shows the distribution of each section of Eye color:</p>
<p>1.Black Eye Color: Broad range of heights with a median around 170cm implicating that High Variability in height among individuals with black eyes.</p>
<p>2.Blue Eye Color: Narrow range around a median of 165cm implicating that Heights are more consistent among those blue eyes.</p>
<p>3.Brown Eye Color:Highest median height below 170 cm ,with narrow variation implicating that Generally taller, with less height variability compared to black eyes.</p>
<p>4.Green Eye Color:Median near 165cm, very tight range implicating that compact height distribution, showing strong central tendency.</p>
<p>5.Hazel Eye Color:Median similar to green eyes, with a broader range implicating moderate variability,with heights centered around the median.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-result2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../../results/figures/scatterplot.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Height and weight stratified by gender.</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatter plot displays the relationship between weight(X-axis) and income(y-axis).The data points are widely dispersed without a clear trend, indicating that there is nos significant relationship or dependency between the weight of individuals and their income in this particular dataset.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-resulttable3" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;3: Linear model fit table.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">195.0790698</td>
<td style="text-align: right;">42.8951725</td>
<td style="text-align: right;">4.5478094</td>
<td style="text-align: right;">0.0104350</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income</td>
<td style="text-align: right;">-0.0004279</td>
<td style="text-align: right;">0.0004122</td>
<td style="text-align: right;">-1.0380663</td>
<td style="text-align: right;">0.3578676</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Eye Color</code>blue</td>
<td style="text-align: right;">15.6825581</td>
<td style="text-align: right;">18.6712442</td>
<td style="text-align: right;">0.8399311</td>
<td style="text-align: right;">0.4482183</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Eye Color</code>brown</td>
<td style="text-align: right;">-2.2069767</td>
<td style="text-align: right;">20.7739821</td>
<td style="text-align: right;">-0.1062375</td>
<td style="text-align: right;">0.9205086</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Eye Color</code>green</td>
<td style="text-align: right;">-0.9953488</td>
<td style="text-align: right;">23.5865057</td>
<td style="text-align: right;">-0.0421999</td>
<td style="text-align: right;">0.9683618</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Eye Color</code>hazel</td>
<td style="text-align: right;">10.0837209</td>
<td style="text-align: right;">21.6599511</td>
<td style="text-align: right;">0.4655468</td>
<td style="text-align: right;">0.6657578</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The regression results indicate that height is modeled with income and eye color as predictors show that 1.Intercept(195, p-value=0.0104): The intercept represents the estimated height when all the predictors are zero.The sisgnificant p-value indicates that this base height is statistically significant.</p>
<p>2.Income (0.000428, p-value = 0.358): The coefficient for income indicates that for each unit increase in income, height is expected to increase by approximately 0.000428 units. The p-value suggests that this effect is not statistically significant, implying there might be no strong linear relationship between income and height.</p>
<p>3.Eye Color Blue (-15.7, p-value = 0.448): This coefficient suggests that individuals with blue eyes are, on average, 15.7 units shorter than the reference eye color category. The high p-value indicates that this difference is not statistically significant.</p>
<p>4.Eye Color Brown (-2.21, p-value = 0.921): Similar to blue, having brown eyes correlates with being 2.21 units shorter than the reference group, but this is also not statistically significant.</p>
<p>5.Eye Color Green (-0.95, p-value = 0.966): This result suggests almost no difference in height compared to the reference eye color, and the effect is not statistically significant.</p>
<p>6.Eye Color Hazel (10.1, p-value = 0.666): This suggests that individuals with hazel eyes are on average 10.1 units taller than the reference group, although this is not statistically significant.</p>
<p>The model suggests that neither income nor eye color has a statistically significant effect on height, based on the p-values associated with each predictor. This implies that variations in height within this dataset are likely due to factors not included in this model. The overall effectiveness of the model in predicting height based on these variables might be limited, indicating potential need for considering other variables or a different modeling approach. # References</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list">
<div id="ref-leek2015" class="csl-entry" role="listitem">
Leek, J. T., &amp; Peng, R. D. (2015). Statistics. <span>What</span> is the question? <em>Science (New York, N.Y.)</em>, <em>347</em>(6228), 1314–1315. <a href="https://doi.org/10.1126/science.aaa6146">https://doi.org/10.1126/science.aaa6146</a>
</div>
<div id="ref-mckay2020" class="csl-entry" role="listitem">
McKay, B., Ebell, M., Billings, W. Z., Dale, A. P., Shen, Y., &amp; Handel, A. (2020). Associations <span>Between Relative Viral Load</span> at <span>Diagnosis</span> and <span>Influenza A Symptoms</span> and <span>Recovery</span>. <em>Open Forum Infectious Diseases</em>, <em>7</em>(11), ofaa494. <a href="https://doi.org/10.1093/ofid/ofaa494">https://doi.org/10.1093/ofid/ofaa494</a>
</div>
<div id="ref-mckay2020a" class="csl-entry" role="listitem">
McKay, B., Ebell, M., Dale, A. P., Shen, Y., &amp; Handel, A. (2020). Virulence-mediated infectiousness and activity trade-offs and their impact on transmission potential of influenza patients. <em>Proceedings. Biological Sciences</em>, <em>287</em>(1927), 20200496. <a href="https://doi.org/10.1098/rspb.2020.0496">https://doi.org/10.1098/rspb.2020.0496</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>